baseURL = "https://aclaudiap.github.io/meu-portfolio-doc/"
languageCode = "pt-br"
title = "Portfólio | Claudia"
theme = "FixIt"

[params]
  defaultTheme = "light"

  [params.home]
    [params.home.profile]
      enable = true
      title = "Olá, eu sou a Claudia"
      subtitle = "Documentação Técnica | Processos | Tecnologia"
      social = true
      
  [params.social]
    GitHub = "aclaudiap"
    Linkedin = "seu-perfil-aqui"
    Email = "seu-email@exemplo.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Documentação"
    url = "/posts"
    weight = 1